from __future__ import annotations  # Until Python 3.14

from collections.abc import Callable
from dataclasses import dataclass, field
from functools import cached_property
from typing import Any, TypeAlias

from smal.schemas.state_machine import SMALFile

SMALMacroContextComputeFn: TypeAlias = Callable[[SMALFile], Any]


@dataclass(frozen=True)
class SMALMacro:
    name: str
    filename: str
    description: str
    params: list[str]
    extra_context: dict[str, Any] = field(default_factory=dict)
    computed_extra_context: dict[str, SMALMacroContextComputeFn] = field(default_factory=dict)

    @cached_property
    def import_path(self) -> str:
        return f"macros/{self.filename}"

    @cached_property
    def signature(self) -> str:
        if self.params:
            return f"{self.name}({', '.join(self.params)})"
        return f"{self.name}()"


class MacroRegistry:
    _macros = {
        "c_autogen_banner": SMALMacro(
            name="c_autogen_banner",
            filename="c_autogen_banner.j2",
            description="Macro that creates a C-style file banner disclosing that the file was autogenerated by SMAL.",
            params=["smal"],
        ),
    }

    def __new__(cls) -> None:
        raise NotImplementedError("MacroRegistry is a namespace class and cannot be instantiated.")

    @classmethod
    def get(cls, name: str) -> SMALMacro:
        if name not in cls._macros:
            raise ValueError(f"Unknown macro: {name}")
        return cls._macros[name]

    @classmethod
    def list_macros(cls) -> list[SMALMacro]:
        return list(cls._macros.values())

    @classmethod
    def list_macro_names(cls) -> list[str]:
        return list(cls._macros.keys())

    @classmethod
    def has_macro(cls, name: str) -> bool:
        return name in cls._macros
